config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :offline, only: [:index], controller: :offline
  resources :home, only: [:index], controller: :home
  resources :about, only: [:index], controller: :about
  resources :campus, only: [:index], controller: :campus
  resources :quality, only: [:index], controller: :quality
  resources :partnerships, only: [:index], controller: :partnerships
  resources :categories, only: [:index, :show], controller: :categories do
    resources :enrollments, controller: :enrollments
  end
  resources :courses, only: [:index, :show], controller: :courses do
    resources :sections, only: [:index, :show], controller: :sections
  end
  resources :articles, only: [:index, :show], controller: :articles
  resources :contact, only: [:index], controller: :contact
  resources :students, only: [:index], controller: :students
  resources :parents, only: [:index], controller: :parents
  resources :tutors, only: [:index], controller: :tutors
  resources :terms_and_conditions, only: [:index], controller: :terms_and_conditions

  # Newsletter
  resource :newsletter, only: [:show], controller: :newsletter do
    member do
      post :subscribe
    end
  end
end

app/models/articles.rb
# frozen_string_literal: true

class Articles < ApplicationRecord
  # Table name
  self.table_name = "magensinus_articles"

  # Concerns
  include Slug

  # Uploaders
  mount_uploader :image_box, Magensinus::AssetUploader
end

app/models/journal/article.rb
# frozen_string_literal: true

module Journal
  class Article < ApplicationRecord
    # Table name
    self.table_name = "journal_articles"

    # Concerns
    include Slug

    # Relationships
    has_many :assets, dependent: :destroy, foreign_key: "journal_article_id", inverse_of: false
    accepts_nested_attributes_for :assets, allow_destroy: true

    # Uploaders
    mount_uploader :thumb_box, Journal::ThumbUploader
    mount_uploader :thumb_box_magestil, Journal::ThumbUploader
    mount_uploader :cover_box_magestil, Journal::CoverUploader
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  # Callbacks
  before_action :articles, only: [:index]
  before_action :journal_articles, only: [:index]
  before_action :journal_article, only: [:show]

  # /articles
  def index
  end

  # /articles/Hgy897jgfv
  def show
  end

  private

  # Articles
  def articles
    @articles = Articles.first!
  end

  # Journal articles
  def journal_articles
    @journal_articles ||= Journal::Article.where(published: true, magestil: true).order(published_at: :desc)
  end

  # Journal article
  def journal_article
    @journal_article = Journal::Article.find_by(slug: params[:id])
  end
end

app/views/articles/_articles.html.haml
/* Content */

.content
  .content-box
    - if object.title.presence
      .content-item
        %h1= object.try(:title)
    - if object.description.presence
      .content-item
        .trix
          = safe_join([object.try(:description).html_safe])

app/views/articles/index.html.haml
/* Index */

.container-top.left
  .breadcrumbs
    .breadcrumbs-box
      .breadcrumbs-item
        = link_to root_path, class: "link small" do
          .icon.left
            = image_tag "icons/back.png"
          = t("home")

.container-middle.left

  = render partial: "articles", locals: { object: @articles }

  .articles
    .articles-box
      - @journal_articles.each do |journal_article|
        .articles-item
          .articles-inner
            = image_tag journal_article.thumb_box_url
          .separator.extra-small
          = link_to article_path(journal_article), class: "link gray" do
            .icon.left
              = image_tag "icons/underscore.png"
            = (journal_article.title).truncate(24)

.container-bottom.left

app/views/articles/show.html.haml
/* Index */

.container-top.left
  / Breadcrumbs
  .breadcrumbs
    .breadcrumbs-box
      .breadcrumbs-item
        = link_to articles_path, class: "link small" do
          .icon.left
            = image_tag "icons/back.png"
          = t("back")

.container-middle.left
  / Content
  .content.col-large-4-3
    .content-box
      .content-item
        - if @journal_article.title.presence
          %h1= @journal_article.try(:title)
        - if @journal_article.description.presence
          .separator.small
          .trix
            = safe_join([@journal_article.try(:description).html_safe])
    .content-box
      - @journal_article.assets.order(position: :asc).each do |asset|
        - if asset.text == true
          .content-item
            .trix
              = safe_join([asset.text_box.html_safe])
        - if asset.image == true
          .content-item
            .media
              = image_tag asset.image_box_url.to_s, class: "altai-center"
        - if asset.video == true
          .content-item
            .media
              %iframe#ytplayer{ allowfullscreen: "", frameborder: "0", height: "369", src: "https://www.youtube.com/embed/#{asset.video_box}", type: "text/html", width: "656" }
  .content.col-large-4-1
    .content-box
      .content-item
        .articles-sidebar
          %h4 Artigos Recentes
          .articles-sidebar-box
            - recent_journal_articles.each do |item|
              .articles-sidebar-item
                = link_to article_path(item), class: "link small gray" do
                  .icon.left
                    = image_tag "icons/underscore.png"
                  = (item.title).truncate(48)
.container-bottom.left