config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :offline, only: [:index], controller: :offline
  resources :home, only: [:index], controller: :home
  resources :about, only: [:index], controller: :about
  resources :campus, only: [:index], controller: :campus
  resources :quality, only: [:index], controller: :quality
  resources :partnerships, only: [:index], controller: :partnerships
  resources :categories, only: [:index, :show], controller: :categories do
    resources :enrollments, controller: :enrollments
  end
  resources :courses, only: [:index, :show], controller: :courses do
    resources :sections, only: [:index, :show], controller: :sections
  end
  resources :articles, only: [:index, :show], controller: :articles
  resources :contact, only: [:index], controller: :contact
  resources :students, only: [:index], controller: :students
  resources :parents, only: [:index], controller: :parents
  resources :tutors, only: [:index], controller: :tutors
  resources :terms_and_conditions, only: [:index], controller: :terms_and_conditions

  # Newsletter
  resource :newsletter, only: [:show], controller: :newsletter do
    member do
      post :subscribe
    end
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  # Callbacks
  before_action :parent, only: [:index]
  before_action :course, only: [:show]
  before_action :categories, only: [:index]

  # /courses
  def index
  end

  # /courses/slug
  def show
    get_sections = @course.sections
    @sections = get_sections.all
    @section = get_sections.first! if get_sections.presence
    @assets = @section.section_assets.order(position: :asc) if @section.presence
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  # Parent
  def parent
    @parent = Courses.first!
  end

  # Course
  def course
    @course ||= Academy::Course.find_by(slug: params[:id])
  end

  # Categories
  def categories
    @categories ||= Academy::Category.where(magensinus: true, published: true).order(position: :asc)
  end
end

app/views/courses/_breadcrumbs.html.haml
/* Breadcrumbs */

.breadcrumbs
  .breadcrumbs-box
    - if params[:action] == "index"
      .breadcrumbs-item
        = link_to root_path, class: "link small" do
          .icon.left
            = image_tag "icons/back.png"
          = t("home")
    - else
      .breadcrumbs-item
        = link_to courses_path, class: "link small" do
          .icon.left
            = image_tag "icons/back.png"
          = t("back")

app/views/courses/_content.html.haml
/* Content */

.content
  .content-box
    .content-item
      - if object.title.presence
        %h1
          - if object.icon_box_magestil.presence
            .icon.left
              = image_tag object.icon_box_magestil_url.to_s
          = object.try(:title)

app/views/courses/_course_thumb.html.haml
/* Course Thumb */

.courses-item
  .courses-right
    - if course.thumb_box.presence
      .figure{ style: "background-image: url(#{image_path course.thumb_box_url.to_s})" }
    - else
      .figure
  .courses-left
    %h3
      - if course.icon_box.presence
        .icon.left
          = image_tag course.icon_box_url.to_s
      = course.title
    .separator.small
    .trix.left
      = safe_join([course.try(:description).html_safe])
    - if course.external == true
      = link_to "Ler Mais", course.url, class: "button large gray left set-theme-#{course.slug}", target: :blank
    - else
      = link_to "Ler Mais", course_path(course), class: "button large gray left set-theme-#{course.slug}"
    - if course.video_box.presence
      = link_to "https://www.youtube.com/embed/#{course.video_box}", "data-featherlight": "iframe", "data-featherlight-iframe-allowfullscreen": "true", "data-featherlight-iframe-frameborder": "0", "data-featherlight-iframe-height": "540", "data-featherlight-iframe-width": "960", class: "link large black right" do
        .icon.left
          = image_tag "icons/video.png"
        Ver Vídeo
  = render "theme", object: course

app/views/courses/_courses.html.haml
/ Courses

- if objects.presence
  .courses
    .courses-box
      - objects.each do |object|
        - if object.title.presence
          .courses-item
            %h2= object.title
        - if object.description.presence
          .courses-item
            = safe_join([object.try(:description).html_safe])
        - object.courses.where(published: true, magensinus: true).each do |course|
          = render "course_thumb", course: course
        .separator.medium

app/views/courses/_parent.html.haml
/* Content */

.content
  .content-box
    - if parent.title.presence
      .content-item
        %h1= parent.try(:title)
    - if parent.description.presence
      .content-item
        .trix
          = safe_join([parent.try(:description).html_safe])
    - if parent.title.presence
      .separator.medium

app/views/courses/_section_ajax.html.haml
/* Section ajax */

- if asset.text == true
  .trixhdfksdhfksdhfkjhsd
    = safe_join([asset.text_box.html_safe])
- if asset.image == true
  .section-content-asset
    .media.auto.altai-center
      = image_tag asset.image_box_url.to_s, class: "altai-center"
- if asset.video == true
  .section-content-asset
    .media.auto.altai-center
      %iframe#ytplayer{ allowfullscreen: "", frameborder: "0", height: "306", src: "https://www.youtube.com/embed/#{asset.video_box}", type: "text/html", width: "544" }

app/views/courses/_section_content.html.haml
/* Section content */

.section-content
  .section-content-box
    .section-content-item
      .section-content-left
        .section-content-inner#ajax-content
          %h3= @section.title
          .separator.extra-small
          - @assets.each do |asset|
            - if asset.text == true
              .trix
                = safe_join([asset.text_box.html_safe])
            - if asset.image == true
              .section-content-asset
                .media.auto.altai-center
                  = image_tag asset.image_box_url.to_s, class: "altai-center"
            - if asset.video == true
              .section-content-asset
                .media.auto.altai-center
                  %iframe#ytplayer{ allowfullscreen: "", frameborder: "0", height: "306", src: "https://www.youtube.com/embed/#{asset.video_box}", type: "text/html", width: "544" }
      .section-content-right
        = render partial: "section_navigation", locals: { course: @course, sections: @sections }

app/views/courses/_section_navigation.html.haml
/* Section navigation */

.section-navigation
  .section-navigation-box
    - sections.each do |section|
      .section-navigation-item
        = link_to section.title, course_section_path(course, section), remote: true, class: "button extra-large gray set-theme-#{course.slug}"
    - if course.image_box.presence
      .section-navigation-item
        = link_to "Componentes de Formação", course.image_box_url.to_s, target: :blank, "data-featherlight": "image", class: "button extra-large gray gallery set-theme-#{course.slug}"
    - if course.document_box.presence
      .section-navigation-item
        = link_to "Descarregar PDF", course.document_box_url.to_s, target: :blank, class: "button extra-large gray set-theme-#{course.slug}"
    - if course.video_box.presence
      .section-navigation-item
        = link_to "Ver Vídeo", "https://www.youtube.com/embed/#{course.video_box}", "data-featherlight": "iframe", "data-featherlight-iframe-allowfullscreen": "true", "data-featherlight-iframe-frameborder": "0", "data-featherlight-iframe-height": "540", "data-featherlight-iframe-width": "960", class: "button extra-large gray set-theme-#{course.slug}"
    .section-navigation-item
      = link_to "Pré-inscrição", category_enrollments_path(course.category), remote: false, class: "button extra-large gray set-theme-#{course.slug}"

app/views/courses/_theme.html.haml
// Courses theme

- cache "set-theme-#{object.slug}" do
  :coffee
    bindTemplate = ->
      primaryButtonColor = [
        "
          background-color: #{object.try(:background_color_one)} !important;
          border: 1px solid #{object.try(:background_color_one)} !important;
          color: #{object.try(:hover_color_one)} !important;
        "
      ]
      secondaryButtonColor = [
        "
          background-color: #{object.try(:background_color_two)} !important;
          border: 1px solid #{object.try(:background_color_two)} !important;
          color: #{object.try(:hover_color_two)} !important;
        "
      ]
      # Button
      $("a.set-theme-#{object.slug}").attr(
        "style",
        primaryButtonColor
      )
      $("a.set-theme-#{object.slug}").hover(->
        $(this).attr(
          "style",
          secondaryButtonColor
        )
      ).mouseout ->
        $(this).attr(
          "style",
          primaryButtonColor
        )
      return
    $(document).on 'turbolinks:load', ->
      bindTemplate()
      Turbolinks.clearCache()
      return

app/views/courses/index.html.haml
/* Index */

.container-top.left
  = render partial: "breadcrumbs"
.container-middle.left
  = render partial: "parent", locals: { parent: @parent }
  = render partial: "courses", locals: { objects: @categories }
.container-bottom.left

app/views/courses/show.html.haml
/* show */

.container-top.left
  = render partial: "breadcrumbs"
.container-middle.left
  = render partial: "content", locals: { object: @course }
  - if @sections.presence
    = render partial: "section_content"
.container-bottom.left
= render "theme", object: @course

app/views/courses/show.js.haml
/* Show */

:plain
  $("#ajax-content").html("#{j render("section_ajax")}");